version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: storedata
        target: /data/db
      - type: volume
        source: mongo-configdb
        target: /data/configdb
volumes:
  storedata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './storedata'
  mongo-configdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './mongo-configdb'
